---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./__tests__/utils/functions.spec.tsx"
postMerge:
  pattern: 
    - "./__tests__/utils/functions.spec.tsx"
postRun:
     command:
        - yarn --version
version: 1.0 
