---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "__tests__/**/*.spec.tsx"
postMerge:
  pattern: 
    - "__tests__/**/*.spec.tsx"
postRun:
     command:
        - yarn --version
version: 1.0 
