framework: jest
postMerge:
  pattern: 
    - "__tests__/*/*.spec.tsx"
preMerge:
  pattern:
    - "__tests__/*/*.spec.tsx"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 1.0 
